server:
  port: 80

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-eureka: true # false表示自己就是注册中心，不用注册自己
    fetchRegistry: true  # false表示自己就是注册中心，不用去注册中心获取其他服务的地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka